### ISSUE TITLE
HEIC image cropping crash 3.19.1 x64

### ISSUE THREAD

**Issue by fcore117** [nomacs/nomacs#1184]
**Describe the bug**
Cannot cut .heic images without instant crash.

**To Reproduce**
1. Open apple heic image
2. Click on Cut, select any area on image you want to cut
3. Press enter or press cut button
4. Instant crash, window gone.

**Expected behavior**
Cuts image like it was with official old version, no crash.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version [22h2]

**Additional context**
If needed i can upload test .heic by request

**Comment by leejuyuu** [comment]
Hello @fcore117, please provide the nomacs version that would crash and the working version. You can find the version number in `? > About nomacs`. This would greatly help us identify the problem.

If possible, a sample image that caused the crash would also help.

**Comment by fcore117** [comment]
3.19.1 like i already mentioned and here is image, try to cut.
[sample.zip](https://github.com/user-attachments/files/17669961/sample.zip)

**Comment by leejuyuu** [comment]
Confirmed on 3.19.1 (ba263741), Arch Linux, Qt 6.8.0.

The following is the stack trace after the crash.

```
terminate called after throwing an instance of 'Exiv2::Error'
  what():  Setting XMP metadata in BMFF images is not supported

Thread 1 "nomacs" received signal SIGABRT, Aborted.
Downloading source file /usr/src/debug/glibc/glibc/nptl/pthread_kill.c
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44                                                                      
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff5ca5463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007ffff5c4c120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff5c334c3 in __GI_abort () at abort.c:79
#4  0x00007ffff7697b2c in __gnu_cxx::__verbose_terminate_handler () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007ffff76adf3a in __cxxabiv1::__terminate (handler=<optimized out>) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007ffff769752a in std::terminate () at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007ffff76ae1f6 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff5ad70e0 <typeinfo for Exiv2::Error>, dest=0x7ffff5870940 <Exiv2::Error::~Error()>)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#8  0x00007ffff583f946 in Exiv2::BmffImage::setXmpData (this=<optimized out>) at /usr/src/debug/exiv2/exiv2-0.28.3/src/bmffimage.cpp:693
#9  0x00007ffff7d4115d in nmc::DkMetaDataT::clearXMPRect() () at /usr/lib/libnomacsCore.so.3
#10 0x00007ffff7d08150 in nmc::DkImageContainer::cropImage(nmc::DkRotatingRect const&, QColor const&, bool) () at /usr/lib/libnomacsCore.so.3
#11 0x00007ffff7caad79 in nmc::DkViewPort::cropImage(nmc::DkRotatingRect const&, QColor const&, bool) () at /usr/lib/libnomacsCore.so.3
#12 0x00007ffff5fb2229 in QtPrivate::QSlotObjectBase::call (this=0x555556289700, r=0x555555f760c0, a=0x7fffffffd430, this=<optimized out>, r=<optimized out>, a=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobjectdefs_impl.h:486
#13 doActivate<false> (sender=<optimized out>, signal_index=<optimized out>, argv=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qobject.cpp:4120
#14 0x00007ffff7b8aafd in nmc::DkEditableRect::cropImageSignal(nmc::DkRotatingRect const&, QColor const&, bool) const () at /usr/lib/libnomacsCore.so.3
#15 0x00007ffff7ccd73d in nmc::DkCropWidget::crop(bool) () at /usr/lib/libnomacsCore.so.3
#16 0x00007ffff7ccd798 in nmc::DkCropWidget::mouseDoubleClickEvent(QMouseEvent*) () at /usr/lib/libnomacsCore.so.3
#17 0x00007ffff6f50f93 in QWidget::event (this=0x55555585f0b0, event=0x7fffffffda20) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidget.cpp:8967
#18 0x00007ffff6efe31a in QApplicationPrivate::notify_helper (this=this@entry=0x55555557d090, receiver=receiver@entry=0x55555585f0b0, e=e@entry=0x7fffffffda20)
    at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3294
#19 0x00007ffff6f028d1 in QApplication::notify (this=<optimized out>, receiver=<optimized out>, e=0x7fffffffda20) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:2772
#20 0x00007ffff5f585a8 in QCoreApplication::notifyInternal2 (receiver=0x55555585f0b0, event=0x7fffffffda20) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1165
#21 0x00007ffff5f585fd in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1623
#22 0x00007ffff6ef61bd in QApplicationPrivate::sendMouseEvent
    (receiver=0x55555585f0b0, event=0x7fffffffda20, alienWidget=<optimized out>, nativeWidget=0x555555614130, buttonDown=<optimized out>, lastMouseReceiver=..., spontaneous=true, onlyDispatchEnterLeave=false) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:2353
#23 0x00007ffff6f6a768 in QWidgetWindow::handleMouseEvent (this=0x5555558fb630, event=0x7fffffffdd60) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidgetwindow.cpp:632
#24 QWidgetWindow::event (this=0x5555558fb630, event=0x7fffffffdd60) at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qwidgetwindow.cpp:298
#25 0x00007ffff6efe31a in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x5555558fb630, e=0x7fffffffdd60)
    at /usr/src/debug/qt6-base/qtbase/src/widgets/kernel/qapplication.cpp:3294
#26 0x00007ffff5f585a8 in QCoreApplication::notifyInternal2 (receiver=0x5555558fb630, event=0x7fffffffdd60) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1165
#27 0x00007ffff5f585fd in QCoreApplication::sendSpontaneousEvent (receiver=<optimized out>, event=<optimized out>)
    at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qcoreapplication.cpp:1623
#28 0x00007ffff658648c in QGuiApplicationPrivate::processMouseEvent (e=0x7fffe0003670) at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qguiapplication.cpp:2501
#29 0x00007ffff6601284 in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at /usr/src/debug/qt6-base/qtbase/src/gui/kernel/qwindowsysteminterface.cpp:1114
#30 0x00007ffff6a4da14 in userEventSourceDispatch (source=<optimized out>) at /usr/src/debug/qt6-base/qtbase/src/gui/platform/unix/qeventdispatcher_glib.cpp:38
#31 0x00007ffff29cc559 in g_main_dispatch (context=0x7fffe8000f30) at ../glib/glib/gmain.c:3357
#32 0x00007ffff2a2f157 in g_main_context_dispatch_unlocked (context=0x7fffe8000f30) at ../glib/glib/gmain.c:4208
#33 g_main_context_iterate_unlocked.isra.0 (context=context@entry=0x7fffe8000f30, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4273
#34 0x00007ffff29cba55 in g_main_context_iteration (context=0x7fffe8000f30, may_block=1) at ../glib/glib/gmain.c:4338
#35 0x00007ffff61bf71d in QEventDispatcherGlib::processEvents (this=0x5555555a3590, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:396
#36 0x00007ffff5f64566 in QEventLoop::processEvents (this=0x7fffffffe1d0, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:100
#37 QEventLoop::exec (this=0x7fffffffe1d0, flags=...) at /usr/src/debug/qt6-base/qtbase/src/corelib/kernel/qeventloop.cpp:191
#38 0x00007ffff5f59a2f in QCoreApplication::exec () at /usr/src/debug/qt6-base/qtbase/src/corelib/global/qflags.h:74
#39 0x000055555555908b in ??? ()
#40 0x00007ffff5c34e08 in __libc_start_call_main (main=main@entry=0x555555557830, argc=argc@entry=1, argv=argv@entry=0x7fffffffe5a8) at ../sysdeps/nptl/libc_start_call_main.h:58
#41 0x00007ffff5c34ecc in __libc_start_main_impl
    (main=0x555555557830, argc=1, argv=0x7fffffffe5a8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe598) at ../csu/libc-start.c:360
#42 0x0000555555559865 in ??? ()
(gdb) 
```

**Comment by novomesk** [comment]
It is important to put code into try-catch block I think.

**Comment by leejuyuu** [comment]
This has been fixed by 5a653870878dce41d6d462519fed435f022181d0. @fcore117, you can test the builds here https://ci.appveyor.com/project/novomesk/nomacs/builds/50980875/artifacts.

**Comment by fcore117** [comment]
Confirming, seems to be working in first run. Tested couple different generation and device .heic files. I even quickly tested some .heif samples from Google just in case.

**Comment by leejuyuu** [comment]
Thanks for testing!
