### ISSUE TITLE
Crash when rotating 8-bit image

### ISSUE THREAD

**Issue by leejuyuu** [nomacs/nomacs#1232]
> I am getting either a segfault or exception thrown from cv::Mat() when constructing the image with 8-bit images. It makes sense since CV_8UC4 is 4 bytes per pixel, and lower bit depths are not being converted to 32-bit.
> 
> 
> 
> Would it  be possible to support common formats here (8,24-bit) without changing too much? If OpenCV supports 64-bit images maybe that could be added too.
> 
>  

 _Originally posted by @scrubbbbs in [843a889](https://github.com/nomacs/nomacs/commit/843a8898d9aca7a4535f3f387a34901c6bc2e9a9#r150796524)_

**Comment by leejuyuu** [comment]
> CV_8UC4 means unsigned 8-bit int for each pixel and 4 channels, so the data is 32-bit. Here I used that because the color should not be relevant here, only that each pixel is 32-bit is important. This works because QImage uses at least 32-bit aligned data and we convert 64-bit images to 32-bit.
> 
> 
> 
> Could you attach the image that caused the crash? I can open an 8-bit image without issue. 

 _Originally posted by @leejuyuu in [843a889](https://github.com/nomacs/nomacs/commit/843a8898d9aca7a4535f3f387a34901c6bc2e9a9#r150798242)_

**Comment by leejuyuu** [comment]
> An 8-bit image (256-color) like GIF for example has *one* 8-bit channel, hence the issue. So for your code to work as-is all qimage pixel formats must be promoted/demoted to 32-bit rgba-8888
> 
> 
> 
> This file has an exif rotation but nomacs will ignore it. However, if you use the rotate function in the toolbar, it will crash.
> 
> 
> 
> [Image](https://github.com/user-attachments/assets/aa88148f-153e-4391-b56e-fa2515017078)
> 
>  

 _Originally posted by @scrubbbbs in [843a889](https://github.com/nomacs/nomacs/commit/843a8898d9aca7a4535f3f387a34901c6bc2e9a9#r150799045)_

**Comment by leejuyuu** [comment]
Confirmed at 26c81093, Arch Linux.

```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.10.0) /usr/src/debug/opencv/opencv/modules/core/src/matrix.cpp:434: error: (-215:Assertion failed) _step >= minstep in function 'Mat'


Thread 1 "nomacs" received signal SIGABRT, Aborted.
0x00007ffff28a53f4 in ?? () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff28a53f4 in ??? () at /usr/lib/libc.so.6
#1  0x00007ffff284c120 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff28334c3 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff6e97b2c in __gnu_cxx::__verbose_terminate_handler
    ()
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#4  0x00007ffff6eadf3a in __cxxabiv1::__terminate
    (handler=<optimized out>)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#5  0x00007ffff6e9752a in std::terminate ()
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#6  0x00007ffff6eae1f6 in __cxxabiv1::__cxa_throw
    (obj=<optimized out>, tinfo=0x7ffff4f93060 <typeinfo for cv::Exception>, dest=0x7ffff451e600 <cv::Exception::~Exception()>)
    at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/eh_throw.cc:98
#7  0x00007ffff426237d in ??? ()
    at /usr/lib/libopencv_core.so.410
#8  0x00007ffff45221b7 in cv::error(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*, int) ()
    at /usr/lib/libopencv_core.so.410
#9  0x00007ffff43cf8e5 in cv::Mat::Mat(int, int, int, void*, unsigned long) () at /usr/lib/libopencv_core.so.410
#10 0x00007ffff7c73c6b in nmc::rotateImageFast
    (img=..., angle=90)
    at /home/tzu-yu/git_repos/nomacs/ImageLounge/src/DkCore/DkImageStorage.cpp:340
#11 0x00007ffff7c732be in nmc::DkImage::rotateImage
    (img=..., angle=90)
    at /home/tzu-yu/git_repos/nomacs/ImageLounge/src/DkCore/DkImageStorage.cpp:251
```
