### ISSUE TITLE
nomacs crash segfault if gtk.FileChooser used without mouse click

### ISSUE THREAD

**Issue by tbqhmhsfamilam** [nomacs/nomacs#219]
Hello, I am having an issue opening files with nomacs on Debian 9 linux with xfce/gtk desktop environment. When I do ctrl+o, it brings up the file chooser, then I press enter to select a file, it crashes nomacs.

**Steps to reproduce:** 
- Launch nomacs
- press ctrl+o to bring up file chooser dialog, optionally use arrow keys to move file selection
- press enter to select file.

**Expected result:**
- File chooser dialog closes, nomacs displays selected file (image)

**Actual result:** 
- Nomacs hangs for a few seconds, then crashes.

If you use the mouse to click the menu options it's fine. This only seems to happen if you're _only_ using the keyboard.

I saw this issue initially with nomacs version 3.8.0 on MX Linux (Debian 9 based distribution using XFCE/gtk environment). I tested also on Debian 9 xfce environment and found the same problem. I did notice this problem does _not_ occur under KDE environment. So I believe the problem is with nomacs' interaction with the gtk.FileChooser. There is no problem when system default open dialog is kdialog under KDE. 

I see in /var/log/messages 
```
May  6 09:35:45 mx kernel: [36577.709012] nomacs[29638]: segfault at 7ffbff7fdfb8 ip 00007efbfdef5938 sp 00007ffbff7fdf70 error 6 in libQt5Gui.so.5.7.1[7efbfdd1b000+51d000]
```

This is what I get running through gdb using the latest nomacs compiled from git with debug symbols. Looks like it gets stuck in a loop.

```
rich@mx:~
$ gdb ~/build/nomacs/ImageLounge/nomacs
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/rich/build/nomacs/ImageLounge/nomacs...done.
(gdb) run
Starting program: /home/rich/build/nomacs/ImageLounge/nomacs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe72ed700 (LWP 30656)]
ok... default settings are set
loading settings from: /home/rich/.local/share/nomacs/settings.ini
[INFO] Hi there
[INFO] my name is nomacs | Image Lounge v 3.8 installed
[New Thread 0x7fffdd2bc700 (LWP 30657)]
[WARNING] QObject::connect: Cannot connect (null)::runPlugin(DkViewPortInterface*, bool) to nmc::DkControlWidget::setPluginWidget(DkViewPortInterface*, bool)
[WARNING] QObject::connect: Cannot connect (null)::applyPluginChanges(bool) to nmc::DkControlWidget::applyPluginChanges(bool)
[WARNING] QObject::connect: Cannot connect (null)::runPlugin(DkPluginContainer*, const QString&) to nmc::DkViewPort::applyPlugin(DkPluginContainer*, const QString&)
[New Thread 0x7fffdca98700 (LWP 30658)]
[INFO] could not load theme from "/home/rich/build/nomacs/ImageLounge/themes/Light Theme.css"
[INFO] CSS loaded from:  ":/nomacs/stylesheet.css"
[INFO] local client created in:  9 ms
[New Thread 0x7fffd63cb700 (LWP 30659)]
[New Thread 0x7fffd5bca700 (LWP 30660)]
[New Thread 0x7fffd53c9700 (LWP 30661)]
[New Thread 0x7fffd4bc8700 (LWP 30662)]
[New Thread 0x7fffcd3df700 (LWP 30663)]
[INFO] LAN client created in:  0 ms
[New Thread 0x7fffccbde700 (LWP 30664)]
[INFO] [thumb] Screenshot-3mod.png (160 x 33) loaded in 3 ms from EXIV
[INFO] Initialization takes:  834 ms
[INFO] [thumb] Screenshot-3.png (160 x 91) loaded in 2 ms from EXIV
[INFO] [thumb] 20180505_202420.jpg (160 x 118) loaded in 1 ms from EXIV
[New Thread 0x7fffc71c6700 (LWP 30665)]
[New Thread 0x7fffc69c5700 (LWP 30666)]
[New Thread 0x7fffc521d700 (LWP 30667)]
[New Thread 0x7fffc4a1c700 (LWP 30668)]
[New Thread 0x7fffb7fff700 (LWP 30669)]
[Thread 0x7fffc4a1c700 (LWP 30668) exited]
[Thread 0x7fffc521d700 (LWP 30667) exited]
os filename:  "/home/rich/Pictures/20180505_202420.jpg"
("20180505_202420.jpg", "MX Linux Logo.png", "Screenshot-1.png", "Screenshot-2.png", "Screenshot-3.png", "Screenshot-3mod.png", "Screenshot.png", "which.jpeg")
[DkImageLoader] 8 containers created in 0 ms
[DkImageLoader] after sorting:  0 ms
[INFO] /home/rich/Pictures [8] loaded in 3 ms
sync mode:  false
I got a file request??
sync mode:  false
I got a file request??
sync mode:  false
I got a file request??
sync mode:  false
I got a file request??
sync mode:  false
I got a file request??
sync mode:  false

REDACTED: repeating, repeating, repeating...

I got a file request??
sync mode:  false
I got a file request??
sync mode:  false
I got a file request??
sync mode:  false
I got a file request??
sync mode:  false
I got a file request??

Thread 1 "nomacs" received signal SIGSEGV, Segmentation fault.
0x00007ffff51d9938 in QTextEngine::justify(QScriptLine const&) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt f
#0  0x00007ffff51d9938 in QTextEngine::justify(QScriptLine const&) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#1  0x00007ffff51da66f in QTextEngine::alignLine(QScriptLine const&) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#2  0x00007ffff51e6cda in QTextLine::cursorToX(int*, QTextLine::Edge) const () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#3  0x00007ffff5852724 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#4  0x00007ffff5852918 in QWidgetTextControl::ensureCursorVisible() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#5  0x00007ffff5851cfa in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#6  0x00007ffff5834031 in QTextEdit::setPlainText(QString const&) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#7  0x00007ffff78d447b in nmc::DkCommentWidget::setComment (this=0x555555915570, description=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkMetaDataWidgets.cpp:1220
No locals.
#8  0x00007ffff78d441e in nmc::DkCommentWidget::setMetaData (this=0x555555915570, metaData=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkMetaDataWidgets.cpp:1215
No locals.
#9  0x00007ffff78902f9 in nmc::DkControlWidget::updateImage (this=0x555555a3d270, imgC=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkControlWidget.cpp:660
        metaData = {value = 0x555555f03e60, d = 0x555555ef9500}
        dateString = {static null = {<No data fields>}, d = 0x7ffff4e77ee0 <QArrayData::shared_null>}
#10 0x00007ffff793f4bd in nmc::DkViewPort::unloadImage (this=0x555555a243f0, fileChange=true) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1573
        success = 1
#11 0x00007ffff793f669 in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1593
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#12 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#13 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#14 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#15 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#16 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#17 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#18 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#19 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#20 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"

REDACTED: repeating, repeating, repeating...

#61491 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#61492 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#61493 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#61494 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#61495 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#61496 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#61497 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#61498 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#61499 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#61500 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"
#61501 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#61502 0x00007ffff7940691 in nmc::DkViewPort::tcpLoadFile (this=0x555555a243f0, idx=0, filename=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1773
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::tcpLoadFile(qint16, QString)"




#61503 0x00007ffff793f89e in nmc::DkViewPort::loadFile (this=0x555555a243f0, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkViewPort.cpp:1606
        __PRETTY_FUNCTION__ = "void nmc::DkViewPort::loadFile(const QString&)"
#61504 0x00007ffff7881753 in nmc::DkCentralWidget::loadFile (this=0x555555ab4050, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkCentralWidget.cpp:1028
No locals.





#61505 0x00007ffff78818a7 in nmc::DkCentralWidget::loadFileToTab (this=0x555555ab4050, filePath=...) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkCentralWidget.cpp:1056
        currentTabIdx = 0
        currentTabMode = nmc::DkTabInfo::tab_empty
#61506 0x00007ffff78ec1cd in nmc::DkNoMacs::openFile (this=0x5555559a8810) at /home/rich/build/nomacs/ImageLounge/src/DkGui/DkNoMacs.cpp:1289
        dup = false
        fileName = {static null = {<No data fields>}, d = 0x555555f51610}
        __for_range = @0x7fffffffcf78: {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x555555917780}, d = 0x555555917780}}, <No data fields>}
        __for_begin = {i = 0x555555917790}
        __for_end = {i = 0x555555917798}
        openFilters = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x55555597d2e0}, d = 0x55555597d2e0}}, <No data fields>}
        fileNames = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x555555917780}, d = 0x555555917780}}, <No data fields>}
        count = 0
        duplicates = {q_hash = {{d = 0x7ffff4e78f80 <QHashData::shared_null>, e = 0x7ffff4e78f80 <QHashData::shared_null>}}}
        __PRETTY_FUNCTION__ = "void nmc::DkNoMacs::openFile()"
#61507 0x00007ffff7a51d46 in nmc::DkNoMacs::qt_static_metacall (_o=0x5555559a8810, _c=QMetaObject::InvokeMetaMethod, _id=27, _a=0x7fffffffd340) at /home/rich/build/nomacs/ImageLounge/nomacsCore_autogen/XJ2BUHI2UY/moc_DkNoMacs.cpp:570
        _t = 0x5555559a8810
#61508 0x00007ffff4dda5e9 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#61509 0x00007ffff568b1c2 in QAction::triggered(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#61510 0x00007ffff568dbb0 in QAction::activate(QAction::ActionEvent) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#61511 0x00007ffff568e52c in QAction::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#61512 0x00007ffff5691b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#61513 0x00007ffff5699341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
No symbol table info available.
#61514 0x00007ffff4dae9e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#61515 0x00007ffff5123198 in QShortcutMap::dispatchEvent(QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#61516 0x00007ffff5123259 in QShortcutMap::tryShortcut(QKeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#61517 0x00007ffff50dbc5d in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#61518 0x00007ffff50f3144 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#61519 0x00007ffff50f8665 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#61520 0x00007ffff50d661b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
No symbol table info available.
#61521 0x00007fffea7494c0 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
No symbol table info available.
#61522 0x00007ffff144c7f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#61523 0x00007ffff144ca60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#61524 0x00007ffff144cb0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#61525 0x00007ffff4e0304f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#61526 0x00007ffff4dac9ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#61527 0x00007ffff4db513c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
No symbol table info available.
#61528 0x000055555556b0d5 in main (argc=1, argv=0x7fffffffe188) at /home/rich/build/nomacs/ImageLounge/src/main.cpp:295
        app = <incomplete type>

        settings = {<QSettings> = {<No data fields>}, <No data fields>}
        mode = 0
        parser = {d = 0x5555559a5700}
        fullScreenOpt = {d = {d = 0x5555559a6c50}}
        pongOpt = {d = {d = 0x5555559a6d80}}
        privateOpt = {d = {d = 0x5555559a6eb0}}
        modeOpt = {d = {d = 0x5555559a7040}}
        sourceDirOpt = {d = {d = 0x5555559a7230}}
        tabOpt = {d = {d = 0x5555559a7420}}
        batchOpt = {d = {d = 0x5555559a7520}}
        batchLogOpt = {d = {d = 0x5555559a76b0}}
        importSettingsOpt = {d = {d = 0x5555559a7960}}
        translationName = {static null = {<No data fields>}, d = 0x5555559a6880}
        translationNameQt = {static null = {<No data fields>}, d = 0x5555559a7a50}
        translator = <incomplete type>
---Type <return> to continue, or q <return> to quit---
        translatorQt = <incomplete type>
        w = 0x5555559a8810
        pw = 0x0
        __PRETTY_FUNCTION__ = "int main(int, char**)"
        dt = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = 0x7ffff4fef880 <QObject::staticMetaObject>, stringdata = 0x7ffff7b03c80 <qt_meta_stringdata_nmc__DkTimer>, data = 0x7ffff7b03cc0 <qt_meta_data_nmc__DkTimer>, static_metacall = 0x7ffff7a3fec0 <nmc::DkTimer::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mTimer = {mds = 68511790}}
        fullScreenMode = 0
        rVal = -1

(gdb) 
```

Please let me know if there's other information I can provide, I am happy to help.

Thanks for your attention.

**Comment by diemmarkus** [comment]
thanks a lot for the stack trace - it helped a lot. I would be very thankful if you can test it again using the current master (in case that's not too complicated : )

**Comment by tbqhmhsfamilam** [comment]
Sure! It's fixed, thank you.
