### ISSUE TITLE
segmentation fault at DkDialogManager::openPrintDialog()

### ISSUE THREAD

**Issue by juppytt** [nomacs/nomacs#875]
**Describe the bug**
Opening the print dialog in a new tab results in segmentation fault, because `DkDialogManager::openPrintDialog()` does not check if the current image `imgC` is null or not.

**To Reproduce**
1. Launch nomacs with image input.
2. Click 'ctrl+t' to open a new tab. (Or, click 'View->New Tab')
4. Click 'ctrl+p' to open the print dialog. (Or, click 'File->Print')
5. Trigger the bug.

**Expected behavior**
The callback function `openPrintDialog()` should not be called when there is no current image, or there should be null check at the callback. 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - Qt-5.15.2
 
**Additional context**
```
==3096558==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7fc65564330d bp 0x7ffe38e1dbd0 sp 0x7ffe38e1da80 T0)
==3096558==The signal is caused by a READ memory access.
==3096558==Hint: address points to the zero page.
#0  0x00007ffff7b6630d in nmc::DkImageContainer::image() () from /home/juhee/project/foxfuzz/programs/nomacs-ori/build/libnomacsCored.so.3
#1  0x00007ffff78d7f67 in nmc::DkDialogManager::openPrintDialog() const () from /home/juhee/project/foxfuzz/programs/nomacs-ori/build/libnomacsCored.so.3
#2  0x00007ffff77259a0 in nmc::DkDialogManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) () from /home/juhee/project/foxfuzz/programs/nomacs-ori/build/libnomacsCored.so.3
#3  0x00007ffff51709c0 in ?? () from /usr/local/Qt-5.15.2/lib/libQt5Core.so.5
#4  0x00007ffff5c108e6 in QAction::triggered(bool) () from /usr/local/Qt-5.15.2/lib/libQt5Widgets.so.5
#5  0x00007ffff5c12fb8 in QAction::activate(QAction::ActionEvent) () from /usr/local/Qt-5.15.2/lib/libQt5Widgets.so.5
#6  0x00007ffff5c138cf in QAction::event(QEvent*) () from /usr/local/Qt-5.15.2/lib/libQt5Widgets.so.5
#7  0x00007ffff5c16dc3 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/local/Qt-5.15.2/lib/libQt5Widgets.so.5
#8  0x00007ffff5c1fbb8 in QApplication::notify(QObject*, QEvent*) () from /usr/local/Qt-5.15.2/lib/libQt5Widgets.so.5
#9  0x00007ffff513997a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/local/Qt-5.15.2/lib/libQt5Core.so.5
#10 0x00007ffff5592e53 in QShortcutMap::dispatchEvent(QKeyEvent*) () from /usr/local/Qt-5.15.2/lib/libQt5Gui.so.5
#11 0x00007ffff55937f3 in QShortcutMap::tryShortcut(QKeyEvent*) () from /usr/local/Qt-5.15.2/lib/libQt5Gui.so.5
#12 0x00007ffff5540c72 in QWindowSystemInterface::handleShortcutEvent(QWindow*, unsigned long, int, QFlags<Qt::KeyboardModifier>, unsigned int, unsigned int, unsigned int, QString const&, bool, unsigned short) ()
   from /usr/local/Qt-5.15.2/lib/libQt5Gui.so.5
#13 0x00007ffff55608b1 in QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) () from /usr/local/Qt-5.15.2/lib/libQt5Gui.so.5
#14 0x00007ffff5565b6b in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/local/Qt-5.15.2/lib/libQt5Gui.so.5
#15 0x00007ffff553d7ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/Qt-5.15.2/lib/libQt5Gui.so.5
#16 0x00007fffef987dde in ?? () from /usr/local/Qt-5.15.2/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#17 0x00007ffff3ad117d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff3ad1400 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff3ad14a3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff5194272 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/Qt-5.15.2/lib/libQt5Core.so.5
#21 0x00007ffff513848b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/local/Qt-5.15.2/lib/libQt5Core.so.5
#22 0x00007ffff5140634 in QCoreApplication::exec() () from /usr/local/Qt-5.15.2/lib/libQt5Core.so.5
#23 0x000000000051de66 in main ()
#24 0x00007ffff4b0b083 in __libc_start_main (main=0x5183a0 <main>, argc=0x2, argv=0x7fffffffde08, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffddf8) at ../csu/libc-start.c:308
#25 0x00000000004208fe in _start ()

```

**Comment by novomesk** [comment]
Thanks for finding and reporting this issue.
