### ISSUE TITLE
Error from Make.py : Filename too long

### ISSUE THREAD

**Issue by stephenboston** [nomacs/nomacs#898]
**Describe the bug**
Make.py throws filename too long error

**To Reproduce**

Following instructions in `nomacs/README.md` (Image Lounge 3.17.0)

    $ git submodule init
    $ git submodule update

     $ python scripts/make.py  /usr/lib/qt6/bin
     
This fails with a python exception `Filename too long`

```

    cmake -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_highgui=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python_tests=OFF -DBUILD_opencv_python_bindings_generator=OFF -DBUILD_opencv_stitiching=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_videoio=OFF -B/mnt/sda/hd2/projects/external/nomacs/3rd-party/build/opencv /mnt/sda/hd2/projects/external/nomacs/3rd-party/opencv
    Traceback (most recent call last):
      File "/mnt/sda/hd2/projects/external/nomacs/scripts/make.py", line 381, in <module>
        configure_libs(params, c)
      File "/mnt/sda/hd2/projects/external/nomacs/scripts/make.py", line 332, in configure_libs
        make_libs(p)
      File "/mnt/sda/hd2/projects/external/nomacs/scripts/make.py", line 277, in make_libs
        build(opencv)
      File "/mnt/sda/hd2/projects/external/nomacs/scripts/utils/build.py", line 21, in build
        sp.run(cmakeconfig, check=True)
      File "/usr/lib/python3.10/subprocess.py", line 503, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.10/subprocess.py", line 1847, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    OSError: [Errno 36] File name too long: 'cmake -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_java_bindings_generator=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_apps=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_calib3d=OFF -DBUILD_opencv_highgui=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_opencv_python_tests=OFF -DBUILD_opencv_python_bindings_generator=OFF -DBUILD_opencv_stitiching=OFF -DBUILD_opencv_video=OFF -DBUILD_opencv_videoio=OFF -B/mnt/sda/hd2/projects/external/nomacs/3rd-party/build/opencv /mnt/sda/hd2/projects/external/nomacs/3rd-party/opencv'



```

**Expected behavior**

Successful make

**Desktop (please complete the following information):**
 -Arch kernel 6.01 with MATE  1.26.01

**Additional context**

**Comment by lukasnobody** [comment]
You're trying to build it Windows way.

Just switch to [right metod](https://github.com/nomacs/nomacs?tab=readme-ov-file#build-nomacs-ubuntu).

**Comment by scrubbbbs** [comment]
make.py is for the Windows/Visual Studio build automation.
